import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";

const CreatePostWizard = () => {
  const { user } = useUser();
  if (!user) return null;
  return (
    <div className="flex w-full gap-4">
      <img
        src={user.profileImageUrl}
        alt="Profile Image"
        className="h-14 w-14 rounded-full"
      />
      <input placeholder="Type some emojis!" className="grow bg-transparent" />
    </div>
  );
};
const Home: NextPage = () => {
  const user = useUser();
  const { data, isLoading } = api.posts.getAll.useQuery();
  if (isLoading) {
    return <div>Loading...</div>;
  }
  if (!data) return <div>Something went wrong</div>;
  return (
    <>
      <Head>
        <title>Twitter-Emoji</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full border-x border-x-slate-300 md:max-w-2xl">
          <div className="flex border-b border-slate-300 p-4 ">
            {!user.isSignedIn && (
              <div className="flex justify-center">
                <SignInButton />
              </div>
            )}
            {user.isSignedIn && <CreatePostWizard />}
            {/* <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" /> */}
          </div>
          <div className="flex flex-col">
            {[...data, ...data]?.map((post) => (
              <div key={post.id} className="border-b border-slate-300 p-7">
                {post.content}
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
